create table if not exists genres
(
    id   BIGINT generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists users
(
    id       BIGINT generated by default as identity primary key,
    name     varchar(255),
    login    varchar(255) not null,
    birthday date         not null,
    email    varchar(255) not null
);

create table if not exists friends
(
	id   BIGINT generated by default as identity primary key,
    user_id   BIGINT,
    friend_id BIGINT,
    foreign key (user_id) references users (id) on delete cascade,
    foreign key (friend_id) references users (id) on delete cascade
);

create table if not exists mpas
(
    id   BIGINT generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists films
(
    id           BIGINT generated by default as identity primary key,
    name         varchar(255) not null,
    release_date date,
    description  varchar(200),
    duration     int,
    mpa    BIGINT,
	foreign key (mpa) references mpas (id) on delete cascade
);


create table if not exists likes
(
	id   BIGINT generated by default as identity primary key,
    film_id BIGINT,
    user_id BIGINT,
    foreign key (film_id) references films (id) on delete cascade,
    foreign key (user_id) references users (id) on delete cascade
);


create table if not exists film_genres
(
	id   BIGINT generated by default as identity primary key,
    film_id  BIGINT,
    genre_id BIGINT,
    foreign key (film_id) references films (id) on delete cascade,
    foreign key (genre_id) references genres (id) on delete cascade
);

